services:
  db:
    image: postgres:16-alpine
    container_name: postgres-hamburgueria
    environment:
      POSTGRES_DB: db_hamburgueria
      POSTGRES_USER: carlos
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: api-hamburgueria
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_hamburgueria
      - SPRING_DATASOURCE_USERNAME=carlos
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  pgdata: